import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.sql.rowset.CachedRowSet;
import javax.sql.rowset.RowSetProvider;

/**
 * Class used to communicate with the SQL Database
 * @author Reeve Baker
 */
public class DBUtil {

    private static final String JDBC_DRIVER = "org.postgresql.Driver";
    private static Connection conn = null;

    /**
     * Creates a connection to the SQL Database
     * 
     * @param PGHOST Host name of the database
     * @param PGDATABASE Name of the database
     * @param PGUSER Username to the database
     * @param PGPASSWORD Password to the database
     * @throws ClassNotFoundException if the database driver class is not found.
     * @throws SQLException if a database access error occurs.
     */
    public static void dbConnect(String PGHOST,String PGDATABASE,String PGUSER,String PGPASSWORD) throws SQLException, ClassNotFoundException {
        String connStr = "jdbc:postgresql://" + PGHOST + ":5432/" + PGDATABASE;
        System.out.println(connStr);
        try {
            Class.forName(JDBC_DRIVER);
            conn = DriverManager.getConnection(connStr, PGUSER, PGPASSWORD);
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
            throw e;
        }

        System.out.println("Connected to database successfully!");
    }

    /**
     * Disconnects from the SQL Database
     * 
     * @throws SQLException if a database access error occurs.
     */
    public static void dbDisconnect() throws SQLException {
        try {
            if (conn != null && !conn.isClosed()) {
                conn.close();
            }
        } catch (Exception e) {
            throw e;
        }
    }

    /**
     * Executes a query through the SQL database
     * 
     * @param queryStmt The SQL statement to query
     * @return the ResultSet generated by the SQL query
     * @throws ClassNotFoundException if the database driver class is not found.
     * @throws SQLException if a database access error occurs.
     */
    public static ResultSet dbExecuteQuery(String queryStmt) throws SQLException, ClassNotFoundException {
        Statement stmt = null;
        ResultSet resultSet = null;
        CachedRowSet crs = null;

        try {
            stmt = conn.createStatement();
            resultSet = stmt.executeQuery(queryStmt);

            crs = RowSetProvider.newFactory().createCachedRowSet();
            crs.populate(resultSet);
        } catch (Exception e) {
            System.err.println(e);
            throw e;
        } finally {
            if (resultSet != null) {
                resultSet.close();
            }

            if (stmt != null) {
                stmt.close();
            }
        }

        return crs;
    }

    /**
     * Executes an update through the SQL Database
     * 
     * @param updateStmt The SQL statement to query
     * @throws ClassNotFoundException if the database driver class is not found.
     * @throws SQLException if a database access error occurs.
     */
    public static void dbExecuteUpdate(String updateStmt) throws SQLException, ClassNotFoundException {
        Statement stmt = null;
        try {
            stmt = conn.createStatement();
            stmt.executeUpdate(updateStmt);
        } catch (Exception e) {
            System.err.println(e);
            throw e;
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }
}