import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.sql.rowset.CachedRowSet;
import javax.sql.rowset.RowSetProvider;

/*
 * @author Reeve Baker
 */
public class DBUtil {

    private static final String JDBC_DRIVER = "org.postgresql.Driver";
    private static Connection conn = null;

    /*
     * @param PGHOST
     * @param PGDATABASE
     * @param PGUSER
     * @param PGPASSWORD
     * @throws SQLException
     * @throws ClassNotFoundException
     */
    public static void dbConnect(String PGHOST,String PGDATABASE,String PGUSER,String PGPASSWORD)throws SQLException, ClassNotFoundException {
        String connStr = "jdbc:postgresql://" + PGHOST + ":5432/" + PGDATABASE;
        System.out.println(connStr);
        try {
            Class.forName(JDBC_DRIVER);
            conn = DriverManager.getConnection(connStr, PGUSER, PGPASSWORD);
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
            throw e;
        }

        System.out.println("Connected to database successfully!");
    }

    /*
     * @throws SQLException
     */
    public static void dbDisconnect() throws SQLException {
        try {
            if (conn != null && !conn.isClosed()) {
                conn.close();
            }
        } catch (Exception e) {
            throw e;
        }
    }

    /*
     * @param queryStmt
     * @return the ResultSet generated by the SQL query
     * @throws SQLException
     * @throws ClassNotFoundException
     */
    public static ResultSet dbExecuteQuery(String queryStmt) throws SQLException, ClassNotFoundException {
        Statement stmt = null;
        ResultSet resultSet = null;
        CachedRowSet crs = null;

        try {
            stmt = conn.createStatement();
            resultSet = stmt.executeQuery(queryStmt);

            crs = RowSetProvider.newFactory().createCachedRowSet();
            crs.populate(resultSet);
        } catch (Exception e) {
            System.err.println(e);
            throw e;
        } finally {
            if (resultSet != null) {
                resultSet.close();
            }

            if (stmt != null) {
                stmt.close();
            }
        }

        return crs;
    }

    /*
     * @param updateStmt
     * @throws SQLException
     * @throws ClassNotFoundException
     */
    public static void dbExecuteUpdate(String updateStmt) throws SQLException, ClassNotFoundException {
        Statement stmt = null;
        try {
            stmt = conn.createStatement();
            stmt.executeUpdate(updateStmt);
        } catch (Exception e) {
            System.err.println(e);
            throw e;
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }
}